{{- if .Values.tls.enable -}}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ template "metrics-server.name" . }}
    chart: {{ template "metrics-server.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "metrics-server.fullname" . }}
type: kubernetes.io/tls
data:
  tls.crt: {{ b64enc .Values.tls.certificate }}
  tls.key: {{ b64enc .Values.tls.key }}
{{- end -}}
